name: Setup prerequisites
description: Setup pnpm and Node.js
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 23.x
        registry-url: https://registry.npmjs.org

    - name: Install pnpm
      run: |
        npm i pnpm@10.10.0 --global && pnpm --version
      shell: bash

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
