import fs from "node:fs";
import path from "node:path";
import { vitePluginTevm } from "tevm/bundler/vite-plugin";
import tsconfigPaths from "vite-tsconfig-paths";
import { defineConfig } from "vocs";

export default defineConfig({
  title: "evmstate",
  description:
    "A TypeScript library for tracing, and visualizing EVM state changes with detailed human-readable labeling.",
  titleTemplate: "%s — evmstate",
  basePath: "/",
  baseUrl: "https://evmstate.polareth.org",
  editLink: {
    pattern: "https://github.com/polareth/evmstate/edit/main/docs/pages/:path",
    text: "Suggest edit on GitHub",
  },
  iconUrl: {
    dark: "/icon-dark.png",
    light: "/icon-light.png",
  },
  logoUrl: {
    dark: "/logo-dark.png",
    light: "/logo-light.png",
  },
  markdown: {
    code: {
      themes: {
        dark: "poimandres",
        light: JSON.parse(fs.readFileSync(path.join(__dirname, "themes/theme-light.json"), "utf8")),
      },
    },
  },
  theme: {
    accentColor: {
      dark: "oklch(0.7 0.12 265)",
      light: "#007ACC",
    },
    variables: {
      color: {
        white: { light: "#FFFFFF", dark: "oklch(0.95 0 0)" },
        black: { light: "#000000", dark: "oklch(0.2 0 0)" },
        // background: { light: "#FFFFFF", dark: "oklch(0.25 0 0)" },
        // background2: { light: "#F5F5F5", dark: "oklch(0.3 0 0)" },
        // background3: { light: "#EEEEEE", dark: "oklch(0.35 0 0)" },
        // background4: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        // background5: { light: "#D0D0D0", dark: "oklch(0.45 0 0)" },
        backgroundAccent: { light: "#E3F2FD", dark: "oklch(0.3 0.05 265)" },
        backgroundAccentHover: { light: "#BBDEFB", dark: "oklch(0.35 0.08 265)" },
        backgroundAccentText: { light: "#0D47A1", dark: "oklch(0.8 0.12 265)" },
        backgroundBlueTint: { light: "#E3F2FD", dark: "oklch(0.3 0.05 265)" },
        // backgroundDark: { light: "#212121", dark: "oklch(0.2 0 0)" },
        backgroundGreenTint: { light: "#E8F5E9", dark: "oklch(0.3 0.05 180)" },
        backgroundGreenTint2: { light: "#C8E6C9", dark: "oklch(0.35 0.08 180)" },
        backgroundIrisTint: { light: "#EDE7F6", dark: "oklch(0.3 0.05 290)" },
        backgroundRedTint: { light: "#FFEBEE", dark: "oklch(0.3 0.05 25)" },
        backgroundRedTint2: { light: "#FFCDD2", dark: "oklch(0.35 0.08 25)" },
        backgroundYellowTint: { light: "#FFF8E1", dark: "oklch(0.3 0.05 90)" },
        border: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        border2: { light: "#BDBDBD", dark: "oklch(0.5 0 0)" },
        borderAccent: { light: "#BBDEFB", dark: "oklch(0.5 0.08 265)" },
        borderBlue: { light: "#BBDEFB", dark: "oklch(0.5 0.08 265)" },
        borderGreen: { light: "#C8E6C9", dark: "oklch(0.5 0.08 180)" },
        borderIris: { light: "#D1C4E9", dark: "oklch(0.5 0.08 290)" },
        borderRed: { light: "#FFCDD2", dark: "oklch(0.5 0.08 25)" },
        borderYellow: { light: "#FFE082", dark: "oklch(0.5 0.08 90)" },
        heading: { light: "#212121", dark: "oklch(0.9 0 0)" },
        shadow: { light: "rgba(0, 0, 0, 0.1)", dark: "rgba(0, 0, 0, 0.3)" },
        text: { light: "#212121", dark: "oklch(0.85 0 0)" },
        text2: { light: "#424242", dark: "oklch(0.75 0 0)" },
        text3: { light: "#616161", dark: "oklch(0.65 0 0)" },
        text4: { light: "#757575", dark: "oklch(0.55 0 0)" },
        textAccent: { light: "#007ACC", dark: "oklch(0.7 0.12 265)" },
        textAccentHover: { light: "#0056B3", dark: "oklch(0.75 0.15 265)" },
        textBlue: { light: "#007ACC", dark: "oklch(0.7 0.12 265)" },
        textBlueHover: { light: "#0056B3", dark: "oklch(0.75 0.15 265)" },
        textGreen: { light: "#228B22", dark: "oklch(0.7 0.12 180)" },
        textGreenHover: { light: "#1B691B", dark: "oklch(0.75 0.15 180)" },
        textIris: { light: "#673AB7", dark: "oklch(0.65 0.15 290)" },
        textIrisHover: { light: "#512DA8", dark: "oklch(0.7 0.18 290)" },
        textRed: { light: "#C62828", dark: "oklch(0.65 0.15 25)" },
        textRedHover: { light: "#B71C1C", dark: "oklch(0.7 0.18 25)" },
        textYellow: { light: "#FFA000", dark: "oklch(0.7 0.15 90)" },
        textYellowHover: { light: "#FF8F00", dark: "oklch(0.75 0.18 90)" },
        blockquoteBorder: { light: "#BBDEFB", dark: "oklch(0.5 0.08 265)" },
        blockquoteText: { light: "#424242", dark: "oklch(0.75 0 0)" },
        // codeBlockBackground: { light: "#F5F5F5", dark: "oklch(0.28 0 0)" },
        // codeCharacterHighlightBackground: { light: "#FFF176", dark: "oklch(0.4 0.1 90)" },
        // codeHighlightBackground: { light: "#E3F2FD", dark: "oklch(0.3 0.05 265)" },
        codeHighlightBorder: { light: "#BBDEFB", dark: "oklch(0.5 0.08 265)" },
        // codeInlineBackground: { light: "#F5F5F5", dark: "oklch(0.3 0 0)" },
        codeInlineBorder: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        codeInlineText: { light: "#C62828", dark: "oklch(0.7 0.12 265)" },
        // codeTitleBackground: { light: "#EEEEEE", dark: "oklch(0.32 0 0)" },
        dangerBackground: { light: "#FFEBEE", dark: "oklch(0.3 0.05 25)" },
        dangerBorder: { light: "#FFCDD2", dark: "oklch(0.5 0.08 25)" },
        dangerText: { light: "#C62828", dark: "oklch(0.65 0.15 25)" },
        dangerTextHover: { light: "#B71C1C", dark: "oklch(0.7 0.18 25)" },
        hr: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        infoBackground: { light: "#E3F2FD", dark: "oklch(0.3 0.05 265)" },
        infoBorder: { light: "#BBDEFB", dark: "oklch(0.5 0.08 265)" },
        infoText: { light: "#007ACC", dark: "oklch(0.7 0.12 265)" },
        infoTextHover: { light: "#0056B3", dark: "oklch(0.75 0.15 265)" },
        lineNumber: { light: "#BDBDBD", dark: "oklch(0.5 0 0)" },
        link: { light: "#007ACC", dark: "oklch(0.7 0.12 265)" },
        linkHover: { light: "#0056B3", dark: "oklch(0.75 0.15 265)" },
        noteBackground: { light: "#F5F5F5", dark: "oklch(0.3 0 0)" },
        noteBorder: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        noteText: { light: "#616161", dark: "oklch(0.65 0 0)" },
        successBackground: { light: "#E8F5E9", dark: "oklch(0.3 0.05 180)" },
        successBorder: { light: "#C8E6C9", dark: "oklch(0.5 0.08 180)" },
        successText: { light: "#228B22", dark: "oklch(0.7 0.12 180)" },
        successTextHover: { light: "#1B691B", dark: "oklch(0.75 0.15 180)" },
        tableBorder: { light: "#E0E0E0", dark: "oklch(0.4 0 0)" },
        // tableHeaderBackground: { light: "#F5F5F5", dark: "oklch(0.3 0 0)" },
        tableHeaderText: { light: "#424242", dark: "oklch(0.75 0 0)" },
        tipBackground: { light: "#EDE7F6", dark: "oklch(0.3 0.05 290)" },
        tipBorder: { light: "#D1C4E9", dark: "oklch(0.5 0.08 290)" },
        tipText: { light: "#673AB7", dark: "oklch(0.65 0.15 290)" },
        tipTextHover: { light: "#512DA8", dark: "oklch(0.7 0.18 290)" },
        warningBackground: { light: "#FFF8E1", dark: "oklch(0.3 0.05 90)" },
        warningBorder: { light: "#FFE082", dark: "oklch(0.5 0.08 90)" },
        warningText: { light: "#FFA000", dark: "oklch(0.7 0.15 90)" },
        warningTextHover: { light: "#FF8F00", dark: "oklch(0.75 0.18 90)" },
      },
    },
  },
  ogImageUrl: "https://vocs.dev/api/og?logo=%logo&title=%title&description=%description",
  rootDir: ".",
  socials: [
    { icon: "github", link: "https://github.com/polareth" },
    { icon: "x", link: "https://twitter.com/polarethorg" },
    { icon: "telegram", link: "https://t.me/polarzer0" },
    { icon: "warpcast", link: "https://warpcast.com/polarzero" },
  ],
  sidebar: [
    {
      text: "Getting started",
      link: "/introduction",
    },
    {
      text: "Guides",
      collapsed: false,
      items: [
        {
          text: "Installation",
          link: "/guides/installation",
        },
        {
          text: "Basic usage",
          link: "/guides/basic-usage",
        },
        {
          text: "Examples",
          link: "/guides/usage-examples",
        },
      ],
    },
    {
      text: "API",
      collapsed: false,
      link: "/api",
      items: [
        {
          text: "traceState",
          link: "/api/trace-state",
        },
        {
          text: "Tracer",
          link: "/api/tracer",
        },
        {
          text: "watchState",
          link: "/api/watch-state",
        },
      ],
    },
    {
      text: "Reference",
      collapsed: false,
      items: [
        {
          text: "Output format",
          link: "/reference/output-format",
        },
        {
          text: "Storage types",
          link: "/reference/storage-types",
        },
      ],
    },
    {
      text: "Playground",
      collapsed: false,
      link: "/playground",
    },
  ],
  topNav: [
    { text: "Getting started", link: "/introduction" },
    { text: "Playground", link: "/playground" },
    { text: "Github", link: "https://github.com/polareth/evmstate" },
  ],
  vite: {
    plugins: [vitePluginTevm({ solc: "0.8.23" }), tsconfigPaths()],
  },
});
